name: CI

on:
  push:
    branches: [ "main" , "release" , "CI_workflows" ]
  pull_request:
    branches: [ "main" , "release" ]

permissions:
  contents: write

jobs:
  testing:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Checkout OASIS
      run: |
        git clone https://gitlab.com/cerfacs/oasis3-mct.git

    - name: Install MPI implementation
      run: |
        sudo apt -y install openmpi-bin libmpich-dev libopenmpi-dev gcc g++ gfortran

    - name: Install NetCDF Library for C and Fortran
      run: |
        sudo apt-get install -y libnetcdf-dev libnetcdff-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.4"
        cache: "pip"

    - name: Install OASIS
      run: |
        cd /home/runner/work/eophis/eophis/oasis3-mct/util/make_dir/
        echo "include /home/runner/work/eophis/eophis/.github/workflows/make.gnu" > make.inc
        sed -i '13s/.*/COUPLE       = \/home\/runner\/work\/eophis\/eophis\/oasis3-mct/' /home/runner/work/eophis/eophis/.github/workflows/make.gnu
        make -f TopMakefileOasis3 pyoasis

    - name: Install eophis
      run: |
        cd /home/runner/work/eophis/eophis/
        pip install .[dev]

    - name: Run Eophis unit tests
      run: |
        source /home/runner/work/eophis/eophis/oasis3-mct/BLD/python/init.sh
        cd /home/runner/work/eophis/eophis/tests/unit_tests
        pytest

    - name: Run operating tests
      run: |
        source /home/runner/work/eophis/eophis/oasis3-mct/BLD/python/init.sh
        cd /home/runner/work/eophis/eophis/tests/
        ./run_all_tests.sh
