name: CI

on:
  push:
    branches: [ "CI_workflows" ]
  pull_request:
    branches: [ "main" , "release" ]

permissions:
  contents: write

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set environment variable
      run: |
        echo "HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "HOME_OASIS=$GITHUB_WORKSPACE/oasis3-mct" >> $GITHUB_ENV
        echo "HOME_EOPHIS=$GITHUB_WORKSPACE/eophis" >> $GITHUB_ENV

    - name: Checkout OASIS
      run: |
        git clone https://gitlab.com/cerfacs/oasis3-mct.git $HOME_OASIS

    - name: Install MPI implementation
      run: |
        sudo apt -y install openmpi-bin libmpich-dev libopenmpi-dev gcc g++ gfortran

    - name: Install NetCDF Library for C and Fortran
      run: |
        sudo apt-get install -y libnetcdf-dev libnetcdff-dev

    - name: Install OASIS
      run: |
        cd $HOME_OASIS
        echo "include $HOME_EOPHIS/.github/workflows/make.gnu" > make.inc
        make -f TopMakefileOasis3 pyoasis

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install eophis
      run: |
        cd $HOME_EOPHIS
        pip install .[dev]

    - name: Run Eophis unit tests
      run: |
        source $HOME_OASIS/BLD/python/init.sh
        cd $HOME_EOPHIS/tests/unit_tests
        pytest

    - name: Run operating tests
      run: |
        source $HOME_OASIS/BLD/python/init.sh
        cd $HOME_EOPHIS/tests/
        ./run_all_tests.sh
