name: Containers

on:
  push:
    branches: [ "CI_workflows" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull ARM64 Ubuntu image
        run: |
          docker pull --platform linux/arm64 ubuntu:latest

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set environment variables
        run: |
          pip install toml
          echo "HOME_DEF=$GITHUB_WORKSPACE/.github/workflows" >> $GITHUB_ENV
          VER=$(python3 -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "VER=$VER" >> $GITHUB_ENV

#      - name: Install Apptainer
#        run: |
#          sudo apt update && sudo apt install -y software-properties-common
#          sudo add-apt-repository -y ppa:apptainer/ppa
#          sudo apt update && sudo apt install -y apptainer
#          sudo apt clean && sudo apt autoclean

#      - name: Build AMD64 image
#        run: |
#          apptainer build eophis_v${VER}_amd64.sif $HOME_DEF/apptainer_eophis.def

      - name: Build ARM64 image
        run: |
          docker run --rm --privileged --platform linux/arm64 -v ${{ github.workspace }}:/workspace -e VER=${{ env.VER }} ubuntu:latest bash -c \
          '   apt update &&
              apt install -y software-properties-common &&
              add-apt-repository -y ppa:apptainer/ppa &&
              apt update &&
              apt install -y apptainer && 
              apptainer build --debug /workspace/eophis_v${VER}_arm64.sif /workspace/.github/workflows/apptainer_eophis.def > /workspace/log.out 2>&1
          '

      - name: lors
        run: |
          cat log.out

      - name: Upload AMD64 Image as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: eophis_v${{ env.VER }}_amd64
          path: ./eophis_v${{ env.VER }}_amd64.sif
          
      - name: Upload ARM64 Image as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: eophis_v${{ env.VER }}_arm64
          path: ./eophis_v${{ env.VER }}_arm64.sif
