name: unit_test

on:
  push:
    branches: [ "main" , "release" , "develop" ]
  pull_request:
    branches: [ "main" , "release" , "develop" ]

permissions:
  contents: write

jobs:
  testing:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Install MPI implementation
      run: |
        sudo apt-get install -y libopenmpi-dev openmpi-bin

    - name: Verify OpenMPI Installation
      run: |
        mpifort --version
        mpicc --version

    - name: Install NetCDF Library for C
      run: |
        sudo apt-get install -y libnetcdf-dev

    - name: Install NetCDF Library for Fortran
      run: |
        sudo apt-get install -y libnetcdff-dev
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.4"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install netcdf4 numpy f90nml pytest watermark
        python -m pip install mpi4py==3.1.5

    - name: Install eophis
      run: |
        cd /home/runner/work/eophis/eophis/
        pip install .
    - name: Run unit tests
      run: |
        cd /home/runner/work/eophis/eophis/tests/unit_tests
        pytest
